### ISSUE TITLE
Guide emoji update fails

### ISSUE THREAD

**Issue by ajax146** [r-Techsupport/TechSupportBot#217]
Bot error in on_guild_emojis_update: 'tuple' object has no attribute 'name'
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/var/basement_bot/base/advanced.py", line 904, in on_guild_emojis_update
    embed.add_field(name="Server", value=before.name)
AttributeError: 'tuple' object has no attribute 'name'
```

**Comment by dkay0670** [comment]
Cannot replicate
