### ISSUE TITLE
Error on cooldown

### ISSUE THREAD

**Issue by TheKrol** [r-Techsupport/TechSupportBot#395]
```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1015, in invoke
    await self.prepare(ctx)
  File "/usr/local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 931, in prepare
    self._prepare_cooldowns(ctx)
  File "/usr/local/lib/python3.11/site-packages/discord/ext/commands/core.py", line 914, in _prepare_cooldowns
    raise CommandOnCooldown(bucket, retry_after, self._buckets.type)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discord.ext.commands.errors.CommandOnCooldown: You are on cooldown. Try again in 25.81s
```
When a command is called while in cooldown, it will give this error.

**Comment by Cpt-Dingus** [comment]
This shluld theoretically be managable using the new errors.py formatting
